artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://diamonds-data.s3.ap-south-1.amazonaws.com/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/diamonds.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/diamonds.csv

model_trainer:
  root_dir: artifacts/model_trainer
  X_train_transformed_path: artifacts\data_transformation\X_train_transformed.csv
  y_train_path: artifacts\data_transformation\y_train.csv
  model_name: model.joblib